### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by herohamp** [feathersjs/feathers-chat#13]
> feathers-chat@0.1.0 start /Users/hamptonmoore/Downloads/feathers-chat-master
> node src/

module.js:327
    throw err;
    ^

Error: Cannot find module 'ee-first'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/hamptonmoore/Downloads/feathers-chat-master/node_modules/feathers/node_modules/express/node_modules/on-finished/index.js:23:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! feathers-chat@0.1.0 start: `node src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-chat@0.1.0 start script 'node src/'.
npm ERR! This is most likely a problem with the feathers-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/
npm ERR! You can get their info via:
npm ERR!     npm owner ls feathers-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MYDIR/Downloads/feathers-chat-master/npm-debug.log

**Comment by ekryski** [comment]
Try upgrading to node v5.x, otherwise you need to run `babel-node`.

**Comment by ekryski** [comment]
Let us know if that didn't work and we can re-open.
