### ISSUE TITLE
Example 'app.publish is not a function'

### ISSUE THREAD

**Issue by JulianHa** [feathersjs/feathers-chat#133]
When I try to follow the example from your website I get the following error: 

>  app.publish(data => app.channel('everybody'));
>     ^
> TypeError: app.publish is not a function
>     at Object.<anonymous> (/home/julian/Desktop/PR06/server/app.js:46:5)
>     at Module._compile (internal/modules/cjs/loader.js:1147:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
>     at Module.load (internal/modules/cjs/loader.js:996:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47

I am running on node v13.10.1

And have copied the exact code from the website: 

```
const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');

// A messages service that allows to create new
// and return all existing messages
class MessageService {
  constructor() {
    this.messages = [];
  }

  async find () {
    // Just return all our messages
    return this.messages;
  }

  async create (data) {
    // The new message is the data merged with a unique identifier
    // using the messages length since it changes whenever we add one
    const message = {
      id: this.messages.length,
      text: data.text
    }

    // Add new message to the list
    this.messages.push(message);

    return message;
  }
}

// Creates an ExpressJS compatible Feathers application
const app = express(feathers());

// Parse HTTP JSON bodies
app.use(express.json());
// Parse URL-encoded params
app.use(express.urlencoded({ extended: true }));
// Host static files from the current folder
app.use(express.static(__dirname));
// Add REST API support
app.configure(express.rest());
// Configure Socket.io real-time APIs
app.configure(socketio());
// Register an in-memory messages service
app.use('/messages', new MessageService());
// Register a nicer error handler than the default Express one
app.use(express.errorHandler());

// Add any new real-time connection to the `everybody` channel
app.on('connection', connection =>
  app.channel('everybody').join(connection)
);
// Publish all events to the `everybody` channel
app.publish(data => app.channel('everybody'));

// Start the server
app.listen(3030).on('listening', () =>
  console.log('Feathers server listening on localhost:3030')
);

// For good measure let's create a message
// So our API doesn't look so empty
app.service('messages').create({
  text: 'Hello world from the server'
});


```

**Comment by JulianHa** [comment]
Changing > app.publish(data => app.channel('everybody'));

to `app.publish((data)` => app.channel('everybody'));
or > app.publish(()=> app.channel('everybody'));

fixes it.
