### ISSUE TITLE
Sample Chat Not Working for MongoDB

### ISSUE THREAD

**Issue by SteveSande** [feathersjs/feathers-chat#283]
In the "Creating an App" section of the docs set the stack to use MongoDB. I had the issue for both TypeScript and JavaScript. Follow the instructions to create the app with GitHub login. See if you also get the following error for Github login:

error: BadRequest: validation failed
    at UserService.<anonymous> (S:\Temp\feathers-chat\node_modules\@feathersjs\schema\lib\hooks\validate.js:47:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Data: [
  {
    instancePath: '/email',
    schemaPath: '#/properties/email/type',
    keyword: 'type',
    params: { type: 'string' },
    message: 'must be string'
  }
]
error: BadRequest: validation failed
    at UserService.<anonymous> (S:\Temp\feathers-chat\node_modules\@feathersjs\schema\lib\hooks\validate.js:47:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Data: [
  {
    instancePath: '/email',
    schemaPath: '#/properties/email/type',
    keyword: 'type',
    params: { type: 'string' },
    message: 'must be string'
  }
]

I was able to get it working when cloning the sample repo and also when creating it myself from the instructions using SQL. I also observed that even when JavaScript was specified the copy buttons for the code snippets still copied TypeScript code and the icon in the top right corner of the code snippet box remains ts.

My system is Windows 10 with VS Code. 
Node.js v16.17.0
Chrome Version 118.0.5993.71

**Comment by NickAguilar93** [comment]
This issue occurs using the mongoDB version of the setup when the user does not have a publicly facing email address for the API to read. If you set a publicly visible email on your GitHub account, this error no longer occurs.
