### ISSUE TITLE
Crashes on npm start

### ISSUE THREAD

**Issue by bitflower** [feathersjs/feathers-chat#77]
Hi there,

thanks for the great approach on this frameworks. Looking forward to trying it out.

However, I get this on boot (Node 6, mongo 3.4, npm 5.6.0)
´´´bash
npm start

> feathers-chat@0.0.0 start /Users/matthias/Documents/Projekte/Temp/feathers-chat
> node src/

/Users/matthias/Documents/Projekte/Temp/feathers-chat/src/hooks/process-message.js:5
  return async context => {
               ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matthias/Documents/Projekte/Temp/feathers-chat/src/services/messages/messages.hooks.js:3:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-chat@0.0.0 start: `node src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-chat@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matthias/.npm/_logs/2017-12-14T21_50_45_000Z-debug.log
```

Any idea? I think your demo is quite up to date?

**Comment by daffl** [comment]
This version has been generated with Node 8 and will only work with that version or later.

**Comment by daffl** [comment]
I added a Note to the Readme.
